worker-threads: 4
worker-fs-threads: 2
logger-level: debug

is_testing: false

server-port: 8080

dbconnection: 'postgresql://pg_service_template_user:password@localhost:5432/pg_service_template_db-1'
